# Author: Studios TKOH!

# Menos ruido en logs
logging.level.root=info
logging.level.org.hibernate.SQL=warn

# Pool de conexiones (Hikari)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Seguridad/headers detr\u00e1s de proxy HTTPS
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
